### ISSUE TITLE
onConnect piece, target bug

### ISSUE THREAD

**Issue by edmund23** [flbulgarelli/headbreaker#23]
While working on issue #22 I noticed something.

When _onConnect(piece, figure, target, targetFigure)_ is executed, piece is always the piece with the lowest ID and target is always the one with the higher ID. So while connecting piece 1 to 2, this is in the correct order. But when connecting piece 2 to 1, then piece is 1 and target is 2.
This kind of makes it impossible to know which tile was dragged.

**Comment by flbulgarelli** [comment]
Hi!

The `onConnect` handler does not actually try to tell which piece was being moved by user input, and the distinction between `piece` and `targetPiece` is merely structural and not related with dragging - when connecting horizontally the connection is always left to right and that way it will be reported, for instance. 

On the other hand, you can register a `TranslationListener` to your pieces and/or puzzles in order to track individual movement. However, please take into account that you won't be able to distinguish between user generated movements and logical translations produced by the "attraction" effect of the near pieces. 

If you need an even more fine grained control, you should interact with [the `konva`](https://konvajs.org/) implementation itself, which does the actual rendering and produces the user events.
