### ISSUE TITLE
Responsive Demo doesn't work in Chrome Version 84.0.4147.105

### ISSUE THREAD

**Issue by jwotman** [flbulgarelli/headbreaker#3]
Puzzle does not resize at all when changing window size.

**Comment by flbulgarelli** [comment]
Hi again! 

Thanks for the report. 

Actually this is probably working, since the _canvas_ :framed_picture:  itself is being resized, which may be not too useful by itself. But what you - and I myself - are probably expecting is that _pieces_ :jigsaw:  are resized, too. I am planning to work this feature in the next few days. 

I am leaving this issue open until the responsive mode support piece resize.

**Comment by jwotman** [comment]
Ah, that makes sense.   That is what I expected.   Maybe pieces can resize proportionally.   Thanks.  I'll check back for this one.

**Comment by flbulgarelli** [comment]
Now the responsive support fully works. Please check the demo!

**Comment by jwotman** [comment]
Looks great!  Thanks so much.
