### ISSUE TITLE
image metadata in autogenerate function fails

### ISSUE THREAD

**Issue by albert-estradera** [flbulgarelli/headbreaker#66]
if you generate a piece with image in metadata with sketchPiece function not fails and show the image, but if the structure is in autogenerate function fails.

Example that works:

labels.sketchPiece({
	structure: { right: headbreaker.Tab },
	metadata: {
			id: 'tree-kanji2',
			color: '#23599E',
			strokeColor: '#18396B',
			**image: {content: document.querySelector("#resumenf"), offset: {x:2, y:1}, scale: 1 }**
	}
});

Example that fails:

labels.autogenerate({
    horizontalPiecesCount: 3,
    verticalPiecesCount: 3,
    metadata: [
		    {color: '#6F04C7', **image: {content: document.querySelector("#resumenf"), offset: {x:21, y:1}, scale: 1 }** }, {color: '#0498D1'}, {color: '#16BA0D'},
		    {color: '#000000'}, {color: '#6F04C7'}, {color: '#0498D1'},
		    {color: '#16BA0D'}, {color: '#000000'}, {color: '#6F04C7'},
    ]
});

thanks

**Comment by flbulgarelli** [comment]
:wave:  Hi @albert-estradera!

Although the way it is failing is - admittedly - not nice at all, `headbreaker` is not designed for that use case at all: you should either sketch pieces individually, passing an image to each of them, or set a per-canvas image and then `autogenerate` the pieces. Passing individual images to each piece may be tricky, since you should take care that all images actually match. 

In other words, I think passing an `image` to `autogenerate`'s `metadata` should throw a validation error, and it might do in the future. 

That said, if you _really_ want to do something like this, you can override the `headbreaker.Metadata.copy`, which is the indirect culprit of your exception. Something like this: 

```javascript
headbreaker.Metadata.__copy__ = headbreaker.Metadata.copy
headbreaker.Metadata.copy = function(it) {
  const dup = this.__copy__(it);
  dup.image = it.image;
  return dup;
}
```

By doing that you will be actually able to use separate images in each piece: 

![image](https://github.com/flbulgarelli/headbreaker/assets/677436/6277d50c-0ce6-4bc6-bd41-d12b01c93654)

```javascript
let xul = new Image();
xul.src = 'static/xul.jpg';
xul.onload = () => {

  const autogen = new headbreaker.Canvas('autogen-canvas', {
    width: 800, height: 650,
    pieceSize: 100, proximity: 20,
    borderFill: 10, strokeWidth: 1.5,
    lineSoftness: 0.18,
  });

  autogen.autogenerate({
    horizontalPiecesCount: 2,
    verticalPiecesCount: 2,
    metadata: [
      { image: { content: xul, offset: { x: 10, y: 10 }, scale: 0.12 } },
      { image: { content: xul, offset: { x: 10, y: 10 }, scale: 0.12 } },
      { image: { content: xul, offset: { x: 10, y: 10 }, scale: 0.12 } },
      { color: '#37AB8C' }
    ]
  });
  autogen.draw();
}
```

However, you should do at your own risk, since as previously said, this framework is not designed to work like that. In other words, overriding `copy` to achieve that goal should be considered just a hack, since - at least by now - this method is exposed to allow more efficient copy strategies, not to alter the copy semantics.
